version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app/src/fastApi
      - ./results:/app/src/fastApi/results
      - ./data:/app/src/fastApi/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"] 