version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8081:8081"
    command: java --add-opens java.base/java.lang=ALL-UNNAMED -Xmx2g -jar webapp-runner.jar backend --port 8081
    volumes:
      - ./results:/app/results
      - ./backend/WEB-INF/classes/inputData:/app/backend/WEB-INF/classes/inputData

  frontend:
    build: .
    ports:
      - "8080:8080"
    command: java -Xmx2g -jar webapp-runner.jar frontend
    volumes:
      - ./results:/app/results